"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ContactRound, ListChecks, NotebookPen, PackageSearch, Plus, ShoppingCart, Trash2 } from "lucide-react";
import { lifeId, loadLifeHub, saveLifeHub } from "@/lib/life-storage";
import type { ContactCategory, LifeHubData, NoteFolder } from "@/lib/life-types";

type Tab="dashboard"|"contacts"|"followups"|"shopping"|"stock"|"notes";
const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
const fmt=(d?:string)=>d?new Date(`${d}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}):"";

export default function LifeHub(){
 const [data,setData]=useState<LifeHubData|null>(null); const [tab,setTab]=useState<Tab>("dashboard");
 useEffect(()=>setData(loadLifeHub()),[]); useEffect(()=>{if(data)saveLifeHub(data)},[data]);
 const overdue=useMemo(()=>data?.followUps.filter(x=>!["Completed","Closed"].includes(x.status)&&x.nextDate<today())??[],[data]);
 const remaining=useMemo(()=>data?.shopping.filter(x=>!x.purchased)??[],[data]);
 const low=useMemo(()=>data?.stock.filter(x=>x.currentQty<=x.minimumQty)??[],[data]);
 if(!data)return <main className="loading-screen">Loading life hub…</main>;
 const del=(key:keyof LifeHubData,id:string)=>setData(x=>x?{...x,[key]:(x[key] as {id:string}[]).filter(v=>v.id!==id)}:x);
 return <div className="shell"><header className="topbar"><div className="brand"><h1>Life Management Hub</h1><p>Contacts, follow-ups, shopping, household stock and organised notes</p></div><Link className="notification-button" href="/"><ArrowLeft size={17}/>Home</Link></header>
 <main className="main"><div className="family-tabs">{(["dashboard","contacts","followups","shopping","stock","notes"] as Tab[]).map(x=><button key={x} className={`quick ${tab===x?"tab-active":""}`} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==="dashboard"&&<><section className="grid three"><Stat title="Overdue follow-ups" value={overdue.length} icon={<ListChecks/>}/><Stat title="Shopping remaining" value={remaining.length} icon={<ShoppingCart/>}/><Stat title="Low stock" value={low.length} icon={<PackageSearch/>}/></section><section className="grid two section-gap"><Box title="Needs attention" items={[...overdue.map(x=>`${x.person}: ${x.subject}`),...low.map(x=>`${x.name} is low`)]}/><Box title="Pinned notes" items={data.notes.filter(x=>x.pinned&&!x.archived).map(x=>x.title)}/></section></>}
 {tab==="contacts"&&<section className="grid two"><ContactForm onSave={v=>setData({...data,contacts:[{id:lifeId(),createdAt:new Date().toISOString(),...v},...data.contacts]})}/><List title="Contacts" empty="No contacts added." rows={data.contacts.map(x=>({id:x.id,title:x.name,meta:`${x.category}${x.company?` • ${x.company}`:""}${x.phone?` • ${x.phone}`:""}`,remove:()=>del("contacts",x.id)}))}/></section>}
 {tab==="followups"&&<section className="grid two"><FollowForm contacts={data.contacts.map(x=>({id:x.id,name:x.name}))} onSave={v=>setData({...data,followUps:[{id:lifeId(),createdAt:new Date().toISOString(),status:"Waiting",...v},...data.followUps]})}/><List title="Follow-ups" empty="No follow-ups added." rows={data.followUps.map(x=>({id:x.id,title:`${x.person}: ${x.subject}`,meta:`${x.status} • next ${fmt(x.nextDate)} • ${x.priority}`,remove:()=>del("followUps",x.id),complete:()=>setData({...data,followUps:data.followUps.map(f=>f.id===x.id?{...f,status:"Completed"}:f)})}))}/></section>}
 {tab==="shopping"&&<section className="grid two"><ShoppingForm onSave={v=>setData({...data,shopping:[{id:lifeId(),createdAt:new Date().toISOString(),purchased:false,...v},...data.shopping]})}/><List title={`Shopping — ${money(remaining.reduce((s,x)=>s+x.estimatedCost,0))} estimated`} empty="No shopping items." rows={data.shopping.map(x=>({id:x.id,title:`${x.name}${x.quantity?` (${x.quantity})`:""}`,meta:`${x.list} • ${money(x.estimatedCost)} • ${x.purchased?"Purchased":"Needed"}`,remove:()=>del("shopping",x.id),complete:()=>setData({...data,shopping:data.shopping.map(i=>i.id===x.id?{...i,purchased:!i.purchased,purchasedDate:!i.purchased?today():undefined}:i)})}))}/></section>}
 {tab==="stock"&&<section className="grid two"><StockForm onSave={v=>setData({...data,stock:[{id:lifeId(),createdAt:new Date().toISOString(),...v},...data.stock]})}/><List title="Household stock" empty="No stock items." rows={data.stock.map(x=>({id:x.id,title:x.name,meta:`${x.currentQty} ${x.unit} • minimum ${x.minimumQty}${x.currentQty<=x.minimumQty?" • LOW STOCK":""}`,remove:()=>del("stock",x.id)}))}/></section>}
 {tab==="notes"&&<section className="grid two"><NoteForm onSave={v=>setData({...data,notes:[{id:lifeId(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),archived:false,...v},...data.notes]})}/><List title="Structured notes" empty="No notes added." rows={data.notes.filter(x=>!x.archived).sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(x=>({id:x.id,title:`${x.pinned?"📌 ":""}${x.title}`,meta:`${x.folder} • ${x.body.slice(0,90)}`,remove:()=>del("notes",x.id),complete:()=>setData({...data,notes:data.notes.map(n=>n.id===x.id?{...n,pinned:!n.pinned,updatedAt:new Date().toISOString()}:n)})}))}/></section>}
 </main></div>
}
function Stat({title,value,icon}:{title:string;value:number;icon:React.ReactNode}){return <article className="card"><div className="card-head"><h2>{title}</h2>{icon}</div><div className="stat">{value}</div></article>}
function Box({title,items}:{title:string;items:string[]}){return <article className="card"><h2>{title}</h2>{items.length?<div className="list">{items.slice(0,8).map((x,i)=><div className="item" key={i}><strong>{x}</strong></div>)}</div>:<p className="muted">Nothing requires attention.</p>}</article>}
function List({title,rows,empty}:{title:string;rows:{id:string;title:string;meta:string;remove:()=>void;complete?:()=>void}[];empty:string}){return <article className="card"><h2>{title}</h2>{rows.length?<div className="list">{rows.map(x=><div className="item" key={x.id}><div><strong>{x.title}</strong><span>{x.meta}</span></div><div className="item-actions">{x.complete&&<button className="icon-button complete-button" onClick={x.complete}><Check size={16}/></button>}<button className="icon-button danger-button" onClick={x.remove}><Trash2 size={16}/></button></div></div>)}</div>:<p className="muted">{empty}</p>}</article>}
function ContactForm({onSave}:{onSave:(v:{name:string;category:ContactCategory;company?:string;phone?:string;email?:string;notes?:string})=>void}){const [name,setName]=useState("");const [category,setCategory]=useState<ContactCategory>("Family");return <SimpleForm title="Add contact" icon={<ContactRound/>} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name,category,company:String(f.get("company")||""),phone:String(f.get("phone")||""),email:String(f.get("email")||""),notes:String(f.get("notes")||"")});setName("")}}><Field label="Name"><input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value as ContactCategory)}>{["Family","Friend","Employer","Client","Candidate","Care Home","GP","Hospital","Solicitor","Accountant","Supplier","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Company"><input name="company"/></Field><Field label="Phone"><input name="phone"/></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Notes" full><textarea name="notes"/></Field></SimpleForm>}
function FollowForm({contacts,onSave}:{contacts:{id:string;name:string}[];onSave:(v:any)=>void}){return <SimpleForm title="Add follow-up" icon={<ListChecks/>} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onSave({...f,nextDate:String(f.nextDate),priority:String(f.priority),contactId:String(f.contactId||"")});e.currentTarget.reset()}}><Field label="Subject" full><input name="subject" required/></Field><Field label="Person / organisation"><input name="person" required/></Field><Field label="Linked contact"><select name="contactId"><option value="">None</option>{contacts.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field label="Channel"><select name="channel"><option>Phone</option><option>Email</option><option>WhatsApp</option><option>In person</option><option>Website</option></select></Field><Field label="Next follow-up"><input name="nextDate" type="date" defaultValue={today()} required/></Field><Field label="Priority"><select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></Field><Field label="Notes" full><textarea name="notes"/></Field></SimpleForm>}
function ShoppingForm({onSave}:{onSave:(v:any)=>void}){return <SimpleForm title="Add shopping item" icon={<ShoppingCart/>} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onSave({...f,estimatedCost:Number(f.estimatedCost||0)});e.currentTarget.reset()}}><Field label="List"><select name="list"><option>Groceries</option><option>Pharmacy</option><option>Home</option><option>Baby</option><option>Car</option><option>Office</option><option>DIY</option></select></Field><Field label="Item"><input name="name" required/></Field><Field label="Quantity"><input name="quantity"/></Field><Field label="Estimated cost (£)"><input name="estimatedCost" type="number" min="0" step="0.01"/></Field></SimpleForm>}
function StockForm({onSave}:{onSave:(v:any)=>void}){return <SimpleForm title="Add household stock" icon={<PackageSearch/>} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onSave({...f,currentQty:Number(f.currentQty),minimumQty:Number(f.minimumQty),averageMonthlyUse:Number(f.averageMonthlyUse||0)});e.currentTarget.reset()}}><Field label="Item"><input name="name" required/></Field><Field label="Category"><input name="category" required/></Field><Field label="Current quantity"><input name="currentQty" type="number" min="0" required/></Field><Field label="Minimum quantity"><input name="minimumQty" type="number" min="0" required/></Field><Field label="Unit"><input name="unit" placeholder="packs, kg, bottles" required/></Field><Field label="Average monthly use"><input name="averageMonthlyUse" type="number" min="0"/></Field></SimpleForm>}
function NoteForm({onSave}:{onSave:(v:any)=>void}){const folders:NoteFolder[]=["Personal","Health","Money","Work","Embrace","Level 7","Family","Vehicles","Other"];return <SimpleForm title="Add structured note" icon={<NotebookPen/>} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));onSave({...f,pinned:f.pinned==="on"});e.currentTarget.reset()}}><Field label="Title" full><input name="title" required/></Field><Field label="Folder"><select name="folder">{folders.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Pinned"><input name="pinned" type="checkbox"/></Field><Field label="Note" full><textarea name="body" required/></Field></SimpleForm>}
function SimpleForm({title,icon,onSubmit,children}:{title:string;icon:React.ReactNode;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){return <article className="card"><div className="card-head"><h2>{title}</h2>{icon}</div><form className="form-grid" onSubmit={onSubmit}>{children}<div className="form-actions full-field"><button className="primary-button compact-button"><Plus size={16}/>Save</button></div></form></article>}
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={`field ${full?"full-field":""}`}>{label}{children}</label>}
